# NixOS System Configuration
# ==========================
# This is the main configuration file for your NixOS system.
#
# Resources:
#   - Manual: `nixos-help` command or https://nixos.org/manual/nixos/stable/
#   - Options search: https://search.nixos.org/options
#   - Package search: https://search.nixos.org/packages
#   - Man page: configuration.nix(5)

{
  config,
  lib,
  pkgs,
  inputs,
  ...
}:

{
  #############################################################################
  ## DRIVERS AND BOOT                                                        ##
  ## Configure hardware drivers and bootloader settings                      ##
  #############################################################################

  imports = [
    # Hardware scan results - auto-generated by nixos-generate-config
    # This file contains hardware-specific configuration like filesystems
    /etc/nixos/hardware-configuration.nix

    # User-specific package configurations
    ./NixModules/userPkgs.nix

    # Laptop-specific settings (currently disabled)
    #./NixModules/laptop.nix

    # NVIDIA graphics configuration (enable if you have an NVIDIA GPU)
    #./NixModules/nvidia.nix

    # Virtualization configuration (libvirt/KVM)
    #./NixModules/virtualization.nix

    # Video decoding hardware acceleration (currently disabled)
    #./NixModules/videoDecoding.nix

    # Spicetify - Spotify customization
    #./NixModules/Spicetify.nix

    # Zed editor configuration
    # ./NixModules/zed.nix

    # Third-party module providing Spicetify integration
    #inputs.spicetify-nix.nixosModules.default
  ];

  # Graphics Configuration
  # ----------------------
  # Enable modern graphics stack (replaces hardware.opengl in newer NixOS)
  hardware.graphics.enable = true;

  # Bootloader Configuration
  # ------------------------
  # systemd-boot is a simple UEFI boot manager. Alternative: GRUB
  boot.loader.systemd-boot.enable = true;

  # Allow NixOS to modify EFI boot variables (required for bootloader updates)
  boot.loader.efi.canTouchEfiVariables = true;

  # Boot Splash Screen (currently disabled)
  # ----------------------------------------
  # Uncomment these for a quieter boot with a splash screen
  #boot.kernelParams = [
  #  "quiet"       # Suppress kernel messages
  #  "splash"      # Show splash screen
  #  "console=tty0" # Redirect console output
  # ];
  #boot.plymouth.enable = true;  # Graphical boot splash

  #############################################################################
  ## SYSTEM                                                                   ##
  ## Core system configuration: networking, time, users, display manager     ##
  #############################################################################

  # NETWORKING
  # ----------
  # Hostname can be set here (currently using default)
  # networking.hostName = "nixos";

  # Wireless networking options (choose one):
  # networking.wireless.enable = true;      # Use wpa_supplicant (manual config)
  networking.networkmanager.enable = true; # Use NetworkManager (GUI-friendly)

  # Time Zone
  # ---------
  # Set system timezone. Affects system clock and scheduling.
  time.timeZone = "America/New_York";

  # Display Manager / Login Screen
  # ------------------------------
  # SDDM - Simple Desktop Display Manager
  services.displayManager.sddm = {
    enable = true;
    wayland.enable = true; # Wayland support
  };

  # Auto-login configuration (uncomment to enable automatic login)
  # WARNING: Enabling auto-login bypasses the login screen
  # services.displayManager.autoLogin = {
  #   enable = true;
  #   user = "YOUR_USERNAME"; # Replace YOUR_USERNAME with your actual username
  # };

  # dms-greeter (currently disabled)
  # --------------------------------
  # dms-greeter is a Wayland-native display manager greeter
  # It handles the login screen and starts your compositor (Hyprland)
  # services.displayManager.dms-greeter = {
  #   enable = true;
  #   compositor.name = "hyprland"; # Compositor to launch after login
  #   configHome = "/home/YOUR_USERNAME"; # Replace YOUR_USERNAME with your actual username
  #   quickshell.package = pkgs.quickshell;
  # };

  # Sudo Configuration
  # ------------------
  # Show asterisks (*) when typing sudo password for visual feedback
  security.sudo.extraConfig = ''
    Defaults pwfeedback
  '';

  # Network Proxy (currently disabled)
  # ----------------------------------
  # Uncomment if you need to use a proxy server
  # networking.proxy.default = "http://user:password@proxy:port/";
  # networking.proxy.noProxy = "127.0.0.1,localhost,internal.domain";

  # Internationalisation (using defaults)
  # -------------------------------------
  # i18n.defaultLocale = "en_US.UTF-8";
  # console = {
  #   font = "Lat2-Terminus16";
  #   keyMap = "us";
  #   useXkbConfig = true; # Use xkb keyboard settings in TTY
  # };

  # Nix Package Manager Settings
  # ----------------------------
  # Enable experimental Nix features for flakes and nix-command
  # Flakes provide reproducible builds; nix-command is the new CLI
  nix.settings.experimental-features = [
    "nix-command"
    "flakes"
  ];

  # Service Discovery
  # -----------------
  # Avahi for printer discovery and other devices on the local network
  services.avahi = {
    enable = true;
    nssmdns4 = true;
    openFirewall = true;
  };

  # Print Server
  # ------------
  # CUPS for printer support with filters
  services.printing = {
    enable = true;
    drivers = with pkgs; [
      cups-filters
      cups-browsed
    ];
  };

  # Auto-mounting for Removable Media
  # ----------------------------------
  # udisks2 allows automatic mounting of USB drives, SD cards, etc.
  services.udisks2.enable = true;

  # Audio Configuration
  # -------------------
  # PipeWire is the modern audio server replacing PulseAudio
  # It provides lower latency and better Bluetooth support
  services.pipewire = {
    enable = true;
    pulse.enable = true; # PulseAudio compatibility layer
  };

  # Touchpad Support
  # ----------------
  # libinput handles input devices. Usually enabled automatically.
  # services.libinput.enable = true;

  # User Account Configuration
  # --------------------------
  # Define the main user account. Set password with `passwd` command.
  # IMPORTANT: Replace YOUR_USERNAME with your actual username!
  users.users.YOUR_USERNAME = {
    isNormalUser = true; # Creates home directory, default shell, etc.
    shell = pkgs.zsh; # Use zsh as default shell
    extraGroups = [
      "wheel" # Enable sudo access
      "libvirtd" # Virtual machine management
    ];
    packages = with pkgs; [
      tree # Directory tree viewer
    ];
  };

  #############################################################################
  ## PROGRAMS                                                                ##
  ## System-wide program configuration and package installation              ##
  #############################################################################

  # Firefox Browser
  # ---------------
  # Enable Firefox with Progressive Web App support
  programs.firefox = {
    enable = true;
    package = pkgs.firefox;
    nativeMessagingHosts.packages = [ pkgs.firefoxpwa ]; # PWA integration
  };

  # System Packages
  # ---------------
  # Packages installed system-wide (available to all users)
  # User-specific packages should go in ./NixModules/userPkgs.nix

  # Allow installation of unfree/proprietary packages
  nixpkgs.config.allowUnfree = true;

  # Environment variable for Wayland compatibility
  # Makes Electron apps and others use Wayland natively
  environment.sessionVariables.NIXOS_OZONE_WL = "1";

  environment.systemPackages = with pkgs; [
    # Clipboard utilities
    wl-clipboard # Wayland clipboard tools (wl-copy, wl-paste)
    cliphist # Clipboard history manager

    # Essential utilities
    wget # File downloader
    git # Version control
    direnv # Directory-specific environment variables

    # Terminal
    kitty # GPU-accelerated terminal emulator

    # Audio utilities
    pavucontrol # PulseAudio volume control (works with PipeWire)
    playerctl # Media player control CLI

    # File manager
    kdePackages.dolphin # KDE file manager

    # System monitoring
    btop # Resource monitor (better htop)
    fastfetch # System info display (neofetch alternative)

    # Theming - Cursors
    rose-pine-hyprcursor # Rose Pine cursor theme for Hyprland
    rose-pine-cursor # Rose Pine XCursor theme

    # Theming - GTK
    adw-gtk3 # Libadwaita theme for GTK3 apps

    # Qt Configuration
    quickshell # Qt-based shell components
    kdePackages.qt6ct # Qt6 configuration tool
    kdePackages.qt5compat # Qt5 compatibility for Qt6
    libsForQt5.qt5ct # Qt5 configuration tool

    # Polkit authentication agent
    hyprpolkitagent # GUI for privilege escalation prompts

    # Hyprland plugins
    inputs.hyprsplit.packages.${pkgs.stdenv.hostPlatform.system}.hyprsplit # Workspace splitting plugin

    # Shell
    zplug # Zsh plugin manager
    zsh-z # Zsh directory jumping
    zsh-powerlevel10k # Zsh theme

    # Networking
    # dnsmasq # Lightweight DNS forwarder/DHCP server
  ];

  # Nix Download Settings
  # ---------------------
  # Increase download buffer size for faster package downloads
  nix.settings.download-buffer-size = 2147483648; # 2GB

  #############################################################################
  ## DESKTOP                                                                 ##
  ## Desktop environment and window manager configuration                    ##
  #############################################################################

  # Hyprland Window Manager
  # -----------------------
  # Hyprland is a dynamic tiling Wayland compositor
  programs.hyprland = {
    enable = true;
    xwayland.enable = true; # X11 application support
  };

  # DMS Desktop Shell
  # -----------------
  # dms-shell provides a complete desktop experience with widgets
  programs.dms-shell = {
    enable = true;

    # Systemd integration for auto-start and service management
    # systemd = {
    #   enable = true; # Run as systemd service
    #   restartIfChanged = true; # Auto-restart on config changes
    # };

    # Feature flags
    enableSystemMonitoring = true; # CPU/RAM widgets (dgop)
    enableVPN = true; # VPN management widget
    enableDynamicTheming = true; # Auto-theming from wallpaper (matugen)
    enableAudioWavelength = true; # Audio visualizer (cava)
    enableCalendarEvents = true; # Calendar integration (khal)
    # enableClipboardPaste = true; # Clipboard history pasting (wtype) (deprecated)

    # Use quickshell from flake input for latest features
    quickshell.package = inputs.quickshell.packages.${pkgs.stdenv.hostPlatform.system}.quickshell;
  };

  # Desktop Search
  # --------------
  programs.dsearch.enable = true;

  # Zsh Shell
  # ---------
  # Enable zsh system-wide. User config in ~/.zshrc
  programs.zsh = {
    enable = true;
  };

  # Application Menu
  # ----------------
  # Use KDE Plasma's application menu format for consistency
  environment.etc."xdg/menus/applications.menu".source =
    "${pkgs.kdePackages.plasma-workspace}/etc/xdg/menus/plasma-applications.menu";

  # XDG Desktop Portal
  # ------------------
  # Portals handle desktop integration: file pickers, screen sharing, etc.
  xdg.portal = {
    enable = true;
    config = {
      hyprland = {
        default = [
          "hyprland" # Hyprland-specific portal (screenshots, etc.)
          "kde" # KDE portal for file picker, etc.
        ];
      };
    };
    configPackages = with pkgs; [
      xdg-desktop-portal-hyprland # Hyprland portal backend
      kdePackages.xdg-desktop-portal-kde # KDE portal backend
    ];
  };

  # Qt Theme Configuration
  # ----------------------
  # Configure Qt applications to use consistent theming
  nixpkgs.config.qt6 = {
    enable = true;
    platformTheme = "qt6ct"; # Use qt6ct for theme configuration
    style = {
      name = "Matugen"; # Material-based theme
    };
  };

  # Fonts
  # -----
  # Install Nerd Fonts for terminal icons and glyphs
  fonts.packages = with pkgs; [
    nerd-fonts.jetbrains-mono
  ];

  #############################################################################
  ## VIRTUALISATION                                                          ##
  ## Virtual machines and container configuration                            ##
  #############################################################################

  # libvirt / KVM Virtual Machines (currently disabled)
  # ---------------------------------------------------
  # Uncomment to enable VM support
  # virtualisation.libvirtd = {
  #   enable = true;
  #   onBoot = "ignore";
  #   onShutdown = "shutdown";
  #   extraConfig = ''
  #     unix_sock_group = "libvirtd"
  #     unix_sock_ro_perms = "0777"
  #     unix_sock_rw_perms = "0770"
  #     auth_unix_ro = "none"
  #     auth_unix_rw = "none"
  #   '';
  # };
  # programs.virt-manager.enable = true;
  # virtualisation.libvirtd.qemu = {
  #   swtpm.enable = true;
  # };

  #############################################################################
  ## MISCELLANEOUS                                                           ##
  ## Other system services and security configuration                        ##
  #############################################################################

  # SUID wrappers and program security (currently disabled)
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # SSH Server (currently disabled)
  # services.openssh.enable = true;

  # Firewall Configuration (currently disabled)
  # networking.firewall.allowedTCPPorts = [ ... ];
  # networking.firewall.allowedUDPPorts = [ ... ];
  # networking.firewall.enable = false;

  # NixOS Version Tracking
  # ----------------------
  # This value determines the NixOS release for compatibility.
  # DO NOT change this unless you understand the migration requirements.
  # It does NOT affect which package versions you receive.
  system.stateVersion = "25.05";

  # Nix-ld: Dynamic Linker Compatibility
  # ------------------------------------
  # Enables running non-NixOS binaries by providing a FHS-compatible loader
  # Useful for running pre-built binaries from the internet
  programs.nix-ld = {
    enable = true;
    libraries = with pkgs; [
      stdenv.cc.cc.lib # C++ standard library
      zlib # Compression library
      # Add additional libraries as needed for specific binaries
    ];
  };
}
